### ISSUE TITLE
PropTypes fail in React 16

### ISSUE THREAD

**Issue by Nickersoft** [mientjan/react-native-markdown-renderer#10]
Hi, just upgraded to React 16 and now using PropTypes from the 'react' module throws an error. Looking through your code, it is being caused by [this line](https://github.com/mientjan/react-native-markdown-renderer/blob/master/lib/renderRules.js#L1). One of your dependencies, `react-native-fit-image`, also causes this issue, but they literally [just merged a fix yesterday](https://github.com/huiseoul/react-native-fit-image/pull/69). I would recommend fixing your own code, then updating the `react-native-fit-image` package as soon as the next version is released with the fix. I'd do it myself.. but even if I fixed the code now, we still have to wait for the maintainers of the other package to release a new version. So just letting you know :)

**Comment by mientjan** [comment]
Thx, really appreciate it. Will take a look at this as soon as possible at this.

**Comment by mientjan** [comment]
This is fixed in release/3.0.0

**Comment by Nickersoft** [comment]
So this issue is actually still occurring, at least for me, seeing the specified version of [react-native-fit-image](https://github.com/huiseoul/react-native-fit-image) in this repo is v1.5.2 and that repo moved to the prop-types dependency just before v1.5.3 was released (see [6f59333](https://github.com/huiseoul/react-native-fit-image/commit/6f5933330c2e9893affc3d2838d358ed18335059)). As a result, that dependency is still trying to look for `React.PropTypes` and is throwing an error. Upgrading the dependencies of this library and pushing a new release should fix all of it.
